# This is a basic workflow to help you get started with Actions

name: transform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [opened, reopened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          # we use version 14.x of node
          node-version: 14.x
      # We now run npm i to install all dependencies and run the "build" script that is defined in the package.json
      - name: Transform design tokens
        run: "npm i && npm run build"

      - name: Transform design tokens
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: transform tokens
